### ISSUE TITLE
大佬能不能提供个openclash的订阅链接？

### ISSUE THREAD

**Issue by Lucktor** [markbang/chromegopacs#2]
大佬能不能提供个openclash的订阅链接？万分感谢！

**Comment by w269368029** [comment]
自己转换订阅不就行了

**Comment by markbang** [comment]
> 大佬能不能提供个openclash的订阅链接？万分感谢！

```
https://chromego-sub.netlify.app/sub/merged_proxies_new.yaml
```
这个和我的项目基本一样的，我懒得写clash配置了，可以用这个链接
来自：https://github.com/Misaka-blog/chromego_merge

**Comment by Luckerleo** [comment]
> 自己转换订阅不就行了
转换订阅试过了，不行，能行就不用再来问了

**Comment by Lucktor** [comment]
> 自己转换订阅不就行了

转换订阅试过了，不行，能行就不用再来问了

**Comment by Lucktor** [comment]
> > 自己转换订阅不就行了
> 
> 转换订阅试过了，不行，能行就不用再来问了

谢谢，这兄弟之前的库好像删库了，又开了一个？

**Comment by markbang** [comment]
> > > 自己转换订阅不就行了
> > 
> > 
> > 转换订阅试过了，不行，能行就不用再来问了
> 
> 谢谢，这兄弟之前的库好像删库了，又开了一个？

不是同一个人
